build page Dashboard
lolliuym/livecom pull request #3
Opened 2022-11-14 16:15 UTC by lolliuym

2022-11-15 14:58 UTC, rubiaqute requested changes
Ты проделал большую работу! Молодец) 
1) Давай изменим структуру. Пусть каждый компонент лежит в своей папке. tsx + css файл. Так будет гораздо удобнее
2) Кстати, будет же несколько страниц в приложении (как по меню)? Не думал роутинг добавить?
По остальным мелким вопросам оставила комментарии.

2022-11-15 14:58 UTC, rubiaqute commented on package.json
>      "tailwindscss": "^0.3.0",
А тебе еще нужен tailwind? Ты же вроде в итоге импортировал стили из бутстраппа. Лучше убирать лишние зависимости

2022-11-15 14:58 UTC, rubiaqute commented on src/App.css
> +.w-30  {
Не советую использовать такое название классов. Уж очень они похожи (а некоторые и совпадают) с теми, что из бутстраппа (см. скрин). В итоге, они у тебя не применяются. Если хочешь писать какие-то общие стили, то лучше придумать им другое название.
![image](https://user-images.githubusercontent.com/79940827/201914052-ae3da283-c8a7-4e71-aa34-b08f0dca03d2.png)

2022-11-15 14:58 UTC, rubiaqute commented on src/App.css
> +}
Здесь и по всему проекту - между стилями должна быть пустая строка. Это улучшает читаемость кода. Можешь поставить на свою IDE расширение stylelint, чтобы было проще

2022-11-15 14:58 UTC, rubiaqute commented on src/assets/styles/listEvents.css
> +  background: #fffc00;
Здесь и по всему проекту цвета выноси в константы.

2022-11-15 14:58 UTC, rubiaqute commented on src/assets/styles/listStories.css
> +  background: url(https://cdn.bootstrapstudio.io/placeholders/1400x800.png) center center / cover no-repeat;display: flex;border-radius: 25px;
В одну строчку css правила писать не стоит. Каждое правило с новой строки

2022-11-15 14:58 UTC, rubiaqute commented on src/components/ActionOfEvents.tsx
> +
Много пустых строк. Одной достаточно

2022-11-15 14:58 UTC, rubiaqute commented on src/components/ActionOfEvents.tsx
> +         <select className="btn btn-outline-secondary w-145 mr-1">
Что-то странные стили для селекта. Немного смущает стилизация выпадающего списка, когда опции выравниваются по центру. Лучше какую-нибудь другую стилизацию взять

2022-11-15 14:58 UTC, rubiaqute commented on src/components/CreatePost.tsx
> +                    <div><FontAwesomeIcon icon={faCamera} /></div>
Список иконок нужно переписать на map

2022-11-15 14:58 UTC, rubiaqute commented on src/components/Header.tsx
> +// import logo from '../../assets/images/logo.png'
Закомментированный код, если не нужен, лучше удалить

2022-11-15 14:58 UTC, rubiaqute commented on src/components/ListEvents.tsx
> +          <div className="w-full thumbnail">
А у тебя здесь нормально с такими классами отображается изображение? У меня оно вылезло на всю страницу, пока не добавила d-flex в обертку

2022-11-15 14:58 UTC, rubiaqute commented on src/components/ListEvents.tsx
> +      <div className="mt-4">
Думаю, если предполагается, что здесь будет несколько мероприятий, советую вытащить карточку одного события в отдельный компонент (который будет принимать изменяемые пропсы), а здесь будет массив из этих карточек, который рендерится через map

2022-11-15 14:58 UTC, rubiaqute commented on src/components/ListStories.tsx
> +      <Swiper
SwiperSlide в отдельный компонент с пропсами, а здесь массив данных и рисуем список слайдов через map

2022-11-15 14:58 UTC, rubiaqute commented on src/components/ListStories.tsx
> +              <div className="slider-avatar">
Кажется div "slider-avatar" - лишняя обертка и тоже можно удалить

2022-11-15 14:58 UTC, rubiaqute commented on src/components/ListStories.tsx
> +                  className="avatar--stories"
А почему здесь имя класса через двойной дефис? Если это из БЭМа, то непохоже на модификатор

2022-11-15 14:58 UTC, rubiaqute commented on src/components/ListStories.tsx
> +          <div className="slider slider-img d-lg-flex justify-content-center align-items-end swiper-slide">
Что-то кажется, что можно className с дива перенести на SwiperSlide и тогда обертку в виде дива удалить

2022-11-15 14:58 UTC, rubiaqute commented on src/components/Sidebar.tsx
> +const Sidebar = () => {
Думаю, стоит прикрутить сюда роутер. Уверена, в react есть какой-то общеиспользуемый пакет. И информацию о menu-items вытащить в массив и рендерить пункты меню с помощью map

2022-11-15 14:58 UTC, rubiaqute commented on src/components/Wordspace.tsx
> +            <h5>Декабрь</h5>
Календарь такого вида подозреваю, что лучше рисовать через слайдер (найти готовое решение где-нибудь в бутстрапе) или написать свой кастомный (опять же через map)

2022-11-15 14:58 UTC, rubiaqute commented on src/components/Wordspace.tsx
> +            <div className="text-center wordspace__date active">
Не поняла что-то: где-то у тебя имена классов через __, где-то через тире, где-то через одинарный _ Лучше, чтоб единообразно было

2022-11-15 14:58 UTC, rubiaqute commented on src/components/Wordspace.tsx
> +          <div className="mt-4">
Лишний див, можно в один класс записать все с предыдущим

2022-11-15 14:58 UTC, rubiaqute commented on src/components/Wordspace.tsx
> +          <h5 className="m-0">Расписание</h5>
Карточку события - в отдельный компонент с пропсами. Здесь рендерим из массива данных с помощью map

2022-11-15 14:58 UTC, rubiaqute commented on package.json
>      "web-vitals": "^2.1.4"
web-vitals - нужен? Если нет, то стоит удалить

2022-11-15 14:58 UTC, rubiaqute commented on src/App.css
> +.-mt-4 {
Не нашла, где класс используется

2022-11-15 14:58 UTC, rubiaqute commented on src/App.css
> +.p-2 {
Не нашла, где используется класс

2022-11-15 14:58 UTC, rubiaqute commented on src/assets/styles/actionOfEvents.css
> +  border: 1px solid lightgrey;
Из-за этого правила артефакт нежелательный на инпуте. Надо удалить

2022-11-15 14:58 UTC, rubiaqute commented on src/components/ActionOfEvents.tsx
> +
Лишние пустые строки

2022-11-15 14:58 UTC, rubiaqute commented on src/components/CreatePost.tsx
> +                  <img className="w-30 h-30 d-lg-flex rounded-circle" width="50px" height="50px" src="../assets/img/avatar.jpg" />
Не поняла, почему резервируешь место под картинку 50х50, а потом в итоге устанавливаешь 30х30.

2022-11-15 14:58 UTC, rubiaqute commented on src/components/ActionOfEvents.tsx
> +            <option value="popular" selected>
Списки в селектах здесь и ниже можно (и нужно) переписать с помощью map + jsx. Думаю, ты в курсе, как. На всякий случай ссылка из документации - https://reactjs.org/docs/lists-and-keys.html. Если будут вопросы - обращайся

2022-11-15 14:58 UTC, rubiaqute commented on src/components/Header.tsx
> +          <img src='../assets/images/logo.png' className="bi me-2" width="40" height="32" alt="LiveCom"/>
Что за класс bi?) Неправильно пропорции подобраны - изображение сплющилось

2022-11-15 14:58 UTC, rubiaqute commented on src/components/Header.tsx
> +          <ul className="dropdown-menu text-small"  >
Будешь свой дропдаун писать? Если нет, то он не заработает, если не импортируешь js из бутстрапа

2022-11-15 14:58 UTC, rubiaqute commented on src/components/ListEvents.tsx
> +                  src="../assets/images/avatar.jpg"
Кстати, у тебя нормально загружаются картинки при разработке? У меня они не грузятся, пока я их не перенесла в папку public и не поменяла пути.

2022-11-16 20:36 UTC, lolliuym commented on src/components/Header.tsx
> +          <ul className="dropdown-menu text-small"  >
да я забыл надо сделать импорт

2022-11-16 20:41 UTC, lolliuym commented on src/components/ActionOfEvents.tsx
> +            <option value="popular" selected>
я в курсе. мне удобно применять это после успешной верстки

2022-11-18 08:59 UTC, lolliuym commented on src/components/ListEvents.tsx
> +                  src="../assets/images/avatar.jpg"
Попробую заменить все рисунки из источника VK.com API

2022-11-22 10:00 UTC, rubiaqute approved these changes

2022-11-22 10:25 UTC, rubiaqute commented
Исправления все посмотрела. Можешь мержить и тогда буду ждать следующий PR.
Пара вопросов:
1. Не наблюдаю в package.json react-router-dom. И пока не установила его, у меня линтер показывал ошибку. Каким образом он у тебя оказался в node_modules, но при этом не фигурирует в package.json?
2. У тебя линтер убрал пробел в правилах css после двоеточия? Некритично, но лучше, чтоб он был. 
Небольшие замечания, которые нужно исправить в следующих коммитах:
1) Очепятки (постаралась подсветить их в комментах)
2) Поехала верстка на странице "Мой профиль" - исправь, пожалуйста
![image](https://user-images.githubusercontent.com/79940827/203287892-fe63f313-8b1a-41f0-b1d9-a882690b69af.png)
3) Логотип сплющен. Надо вернуть ему пропорции
![image](https://user-images.githubusercontent.com/79940827/203288451-addcc2a9-6136-4b22-9bc6-f65f3a5791ba.png)

2022-11-22 10:25 UTC, rubiaqute commented on src/components/Header/Header.tsx
> +            <li><a className="dropdown-item" href="#">Настройа</a></li>
Настройка

2022-11-22 10:25 UTC, rubiaqute commented on src/components/ActionOfEvents/ActionOfEvents.tsx
> +            <option value="evening-parties">Вечерники</option>
Вечеринки же?) Или именно вечерники?

2022-11-22 10:25 UTC, rubiaqute commented on src/components/ProfileHeader/ProfileHeader.tsx
> +              <h6>Ни дня без азартов</h6>
Ни дня без азарта

2022-11-22 10:25 UTC, rubiaqute commented on src/components/Sidebar/Sidebar.tsx
> +            Фотогравии
Фотографии

2022-11-29 06:53 UTC, lolliuym commented on src/components/ActionOfEvents/ActionOfEvents.tsx
> +            <option value="evening-parties">Вечерники</option>
взял данные из источника VK.com
![image](https://user-images.githubusercontent.com/10941111/204459418-62047820-d3c4-4560-bc5f-5a7907e5c551.png)

2022-11-29 13:28 UTC, rubiaqute commented on src/components/CreateEvent/CreateEvent.jsx
> +  const arrayOfClocks = [
Ууууух) 
Лучше использовать методы массивов и строк
  const getStringDigits = (length) => new Array(length).fill(0).map((el, index) => String(el + index).padStart(2,'0'))

  const arrayOfClocks = getStringDigits(24);
  const arrayOfMinutes = getStringDigits(60);

2022-11-29 13:28 UTC, rubiaqute commented on src/components/CreateEvent/CreateEvent.jsx
> +                      Отмен
ОтменаА

2022-11-29 13:28 UTC, rubiaqute commented on src/components/CreateEvent/CreateEvent.jsx
> +                        Адресс
Адрес и ниже - "Указать адрес"

2022-11-29 13:28 UTC, rubiaqute commented on src/components/ActionOfEvents/ActionOfEvents.jsx
> +
Можно добавить массив: const themeOptions = [
    {
      value: "all - teams",
      label: "Все",
    },
    {
      value: "art",
      label: "Искусство и культура",
    },

    и тд и тп
  ];
И тогда в optgroup записать:
          
![image](https://user-images.githubusercontent.com/79940827/204535974-45446346-229d-4d9f-aede-b39008c8d85e.png)
Попробуй сделать по аналогии с опциями с ценами. id не должно повторяться

2022-11-29 13:28 UTC, rubiaqute commented on src/components/ListEvents/ListEvents.jsx
> +      <div className="mt-4 wrapper">
Тут прям просится отдельный компонет на карточку события и рендеринг через map

2022-11-29 13:28 UTC, rubiaqute commented on src/components/Wordspace/Wordspace.jsx
> +const Wordspace = () => {
Можно добавить динамические даты, чтобы не одна и та же в свайпе крутилась
![image](https://user-images.githubusercontent.com/79940827/204540672-347c3a82-a195-4567-a2d3-6378115c3b72.png)
Тогда в самом компоненте можно переписать:
![image](https://user-images.githubusercontent.com/79940827/204540826-fdf929d1-9b6e-489a-9d89-8c7f1e826bef.png)

2022-11-29 13:31 UTC, rubiaqute commented on src/components/ActionOfEvents/ActionOfEvents.tsx
> +            <option value="evening-parties">Вечерники</option>
Тогда замени на вечерИНки. А то вечерНИки - это из другой оперы:)

2022-11-29 15:21 UTC, lolliuym commented on src/components/CreateEvent/CreateEvent.jsx
> +  const arrayOfClocks = [
Профи)

2022-12-06 08:27 UTC, merged